//! 启动 / 停止 dsh web：用自带的官方 Node（--expose-internals）跑 dsh/bin.js，从输出里抓 URL。
use crate::paths::{dsh_bin, node_binary, uv_binary, venv_bin_dir, venv_python, AppPaths};
use serde::Serialize;
use std::fs;
use std::io::{BufRead, BufReader, Write};
#[allow(unused_imports)]
use std::path::PathBuf;
use std::path::Path;
use std::process::{Child, Command, Stdio};
use std::sync::{Arc, Mutex};
use tauri::{AppHandle, Emitter};

#[derive(Clone, Serialize, Default)]
pub struct DshStatus {
    pub state: String, // stopped | starting | running | error
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub log: Vec<String>,
}

/// 把我们的外观选择同步给 dsh（settings.yaml 里的 ui-theme.preference：light / dark / system）
pub fn set_theme(paths: &AppPaths, theme: &str) {
    let f = paths.dsh_home.join("settings.yaml");
    let txt = fs::read_to_string(&f).unwrap_or_default();
    let mut out: Vec<String> = Vec::new();
    let mut skip = false;
    for line in txt.lines() {
        if line.starts_with("ui-theme:") { skip = true; continue; }
        if skip { if line.starts_with(' ') || line.starts_with('\t') || line.trim().is_empty() { continue; } skip = false; }
        out.push(line.to_string());
    }
    out.push("ui-theme:".into());
    out.push(format!("  preference: {theme}"));
    let _ = fs::write(&f, out.join("\n") + "\n");
}

/// 同步界面语言给 dsh（settings.yaml 的 locale.preference：zh / en；system 则按系统语言）
pub fn set_locale(paths: &AppPaths, language: &str) {
    let lang = match language { "en" => "en", "zh" => "zh", _ => if sys_locale_is_zh() { "zh" } else { "en" } };
    let f = paths.dsh_home.join("settings.yaml");
    let txt = fs::read_to_string(&f).unwrap_or_default();
    let mut out: Vec<String> = Vec::new();
    let mut skip = false;
    for line in txt.lines() {
        if line.starts_with("locale:") { skip = true; continue; }
        if skip { if line.starts_with(' ') || line.starts_with('\t') || line.trim().is_empty() { continue; } skip = false; }
        out.push(line.to_string());
    }
    out.push("locale:".into());
    out.push(format!("  preference: {lang}"));
    let _ = fs::write(&f, out.join("\n") + "\n");
}

fn sys_locale_is_zh() -> bool {
    for k in ["LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE"] { if let Ok(v) = std::env::var(k) { if !v.is_empty() { return v.to_lowercase().starts_with("zh"); } } }
    #[cfg(windows)]
    {
        // 读 Windows 用户界面语言（HKCU\Control Panel\International\LocaleName）
        if let Ok(out) = { use std::os::windows::process::CommandExt; std::process::Command::new("reg").args(["query", "HKCU\\Control Panel\\International", "/v", "LocaleName"]).creation_flags(0x0800_0000).output() } {
            let s = String::from_utf8_lossy(&out.stdout).to_lowercase();
            return s.contains("zh-");
        }
    }
    true
}

/// 离线模式：把内网/本地模型接口写进 dsh 的 llm-deepseek 设置段；在线模式移除该段（回到 DeepSeek 官方）。
pub fn set_llm_override(paths: &AppPaths, offline: Option<(&str, &str)>) {
    let f = paths.dsh_home.join("settings.yaml");
    let txt = fs::read_to_string(&f).unwrap_or_default();
    let mut out: Vec<String> = Vec::new();
    let mut skip = false;
    for line in txt.lines() {
        if line.starts_with("llm-deepseek:") { skip = true; continue; }
        if skip { if line.starts_with(' ') || line.starts_with('\t') || line.trim().is_empty() { continue; } skip = false; }
        out.push(line.to_string());
    }
    if let Some((base, model)) = offline {
        out.push("llm-deepseek:".into());
        out.push(format!("  baseURL: {base}"));
        out.push("  apiKeyEnv: BIODSH_OFFLINE_KEY".into());
        if !model.is_empty() {
            out.push("  models:".into());
            out.push(format!("    - id: {model}"));
            out.push(format!("      name: {model}"));
        }
    }
    let _ = fs::write(&f, out.join("\n") + "\n");
}

/// YAML 单引号字符串（单引号翻倍转义）
fn yaml_str(v: &str) -> String { format!("'{}'", v.replace('\'', "''")) }

/// dsh 的沙盒只允许写工作区和会话私有的临时目录；numba / matplotlib 默认往用户目录写缓存，
/// 写不进去就会反复重编译（示范项目里 pbmc3k 预处理因此跑了 40 分钟）。sitecustomize 在每个 Python 进程
/// 启动时把这些缓存指到系统临时目录（沙盒对它有写权限）。
pub fn ensure_sitecustomize(bioenv: &Path) {
    let sp = if cfg!(windows) { bioenv.join(".venv").join("Lib").join("site-packages") } else {
        let lib = bioenv.join(".venv").join("lib");
        match fs::read_dir(&lib).ok().and_then(|rd| rd.flatten().find(|e| e.file_name().to_string_lossy().starts_with("python"))) { Some(e) => e.path().join("site-packages"), None => return }
    };
    if !sp.exists() { return; }
    let f = sp.join("sitecustomize.py");
    let body = "# biodsh-sitecustomize v1 — generated by BioDSH desktop (rewritten on every start)\nimport os, tempfile\ndef _d(name):\n    p = os.path.join(tempfile.gettempdir(), 'biodsh-' + name)\n    try:\n        os.makedirs(p, exist_ok=True)\n        return p\n    except Exception:\n        return None\nfor var, name in (('NUMBA_CACHE_DIR', 'numba'), ('MPLCONFIGDIR', 'matplotlib'), ('XDG_CACHE_HOME', 'cache')):\n    if not os.environ.get(var):\n        p = _d(name)\n        if p: os.environ[var] = p\n";
    if fs::read_to_string(&f).map(|t| t == body).unwrap_or(false) { return; }
    let _ = fs::write(&f, body);
}

pub struct DshManager {
    pub status: Mutex<DshStatus>,
    child: Mutex<Option<Child>>,
}

const PERSONA: &str = "You are BioDSH (中文名同样叫 BioDSH), the built-in bioinformatics assistant of the BioDSH desktop app, powered by the {{model}} model. Your users are doctors and wet-lab scientists with NO programming or bioinformatics background. Your working directory (their project folder) is {{cwd}}.\n\nIdentity: when greeted or asked who you are / what you can do, introduce yourself as BioDSH 生信助手 and give 3 concrete examples they can ask, e.g. 「帮我看看这份单细胞数据的质量」「比较有效和无效病人的细胞组成差异」「解读这个结果文件夹」. Never call yourself a generic coding agent.\n\nYou also know the BioDSH app itself and answer how-to questions about it:\n- 左侧栏「数据」: files in the workspace grouped by type; each file has a 让智能体分析 button; finished analyses appear as result cards with figure thumbnails and a 让智能体解读 button.\n- 「技能商店」: official skills (evaluated, offline, reproducible: single-cell QC/clustering/annotation/treatment-response, plus 电脑控制 desktop-control, AI 科研插图 image-generate, Zotero 联动 zotero-connect, SPSS/R/Prism/Excel 格式桥接 data-format-bridge) and 2,000+ community skills in Chinese categories; click 获取 to install; rate installed skills 👍/👎 in the detail page.
- 「数据库」: 19 public databases with a 让智能体抓取 button, and 本地参考包 (MSigDB gene sets, GO, NCBI gene_info, STRING) downloaded to the folder in env BIODSH_REFDATA (see its README.md) — prefer these local files for enrichment / ID mapping when present.
- 示范项目: 4 real example projects (示范 · 单细胞分析与作图 / 文献调研 / 公共数据库抓取 / 电脑控制与 Zotero) appear in the left project list; each folder has 示范对话.md with the full conversation to imitate.
- 「更多 → 图像生成」 sets the image provider used by image-generate; 「更多 → MCP 接入」 attaches external MCP tool servers (their tools are named mcp__<server>__<tool>).\n- 「分析环境」: one-click Python environment (scanpy etc.); skills need it installed once.\n- 「更多」(settings): DeepSeek API key, workspace folder, 在线/纯离线模式 (offline mode uses a local/intranet model endpoint or a lab Linux dsh server), language 中文/English, theme, version & update check.\n- Right-click anywhere in the app: a \"问一下\" popup explains what things are; right-click a chat in the left sidebar to pin/rename/archive/export; right-click a project for git 版本快照.\n- Data safety: everything runs locally; original data files are never modified; each analysis writes into a new subfolder.\nIf asked about an app detail you are not sure of, say so and point to the closest page instead of inventing UI.\n\nHow you work on analyses:\n- Reply in the language the user writes in. Plain language first, technical detail second; briefly explain any format/tool/statistic you mention.\n- Installed skills are listed for you; when a task matches one, use it and follow its SKILL.md. `python` on PATH is the BioDSH analysis environment (scanpy, anndata, pandas, matplotlib); `uv pip install <pkg>` adds extras.\n- Keep original data untouched; write outputs to a new subfolder and tell the user its name.\n- Whenever you produce or mention an image file (png/jpg/svg) for the user, ALSO show it inline: the env var BIODSH_FILES_URL (read it with `$env:BIODSH_FILES_URL` in pwsh or `echo $BIODSH_FILES_URL`) is a local read-only image server; write `![说明](<BIODSH_FILES_URL>/<absolute file path, forward slashes, spaces as %20>)` right after the file name in your reply, one per figure. Never invent a URL if the variable is empty — just name the file.\n- When a decision is needed (thresholds, which group is control), ask one clear question instead of guessing.";

const MINIMAL_PLUGINS: &[&str] = &[
    "ui-workflow-run", "ui-deliverables", "ui-jobs", "ui-goal", "ui-plan", "ui-trajectory", "ui-subagent",
    "ui-settings-plugin-inventory", "ui-settings-plugins", "ui-cordis", "ui-brand-official", "ui-message-feedback",
    "ui-reference", "ui-agent-preset", "ui-sidebar",
];

impl DshManager {
    pub fn new() -> Self {
        DshManager { status: Mutex::new(DshStatus { state: "stopped".into(), ..Default::default() }), child: Mutex::new(None) }
    }

    fn emit(&self, app: &AppHandle) {
        let s = self.status.lock().unwrap().clone();
        let _ = app.emit("event", serde_json::json!({ "type": "dsh", "status": s }));
    }

    fn push(&self, app: &AppHandle, paths: &AppPaths, line: &str) {
        if let Ok(mut f) = fs::OpenOptions::new().create(true).append(true).open(paths.logs.join("dsh.log")) {
            let _ = writeln!(f, "{line}");
        }
        let mut s = self.status.lock().unwrap();
        s.log.push(line.to_string());
        if s.log.len() > 400 { let n = s.log.len() - 400; s.log.drain(0..n); }
        drop(s);
        self.emit(app);
    }

    /// 精简模式：关掉一问一答用不到的界面插件；写默认设置；预置工作区。
    fn ensure_home(paths: &AppPaths, workspace: &str, preset_src: &Path, mcp: &[crate::settings::McpServer]) {
        let home = &paths.dsh_home;
        // biodsh 预设：复制 standard 组合，仅替换 persona 行 —— 预设层人设会覆盖全局人设，
        // 所以必须在预设里换，全局 system-prompt 只是兜底。
        let preset_ok = (|| -> Option<()> {
            let src = fs::read_to_string(preset_src.join("agent.cordis.yml")).ok()?;
            let coding = "      You are a coding agent powered by the {{model}} model. Your working directory is {{cwd}}.";
            if !src.contains(coding) { return None; }
            let persona_yaml = PERSONA.lines().map(|l| if l.is_empty() { String::new() } else { format!("      {l}") }).collect::<Vec<_>>().join("\n");
            let composed = format!("# biodsh-preset v1 — 由 BioDSH 桌面版自动生成（每次启动重建，请勿手改）\n{}", src.replace(coding, &persona_yaml));
            let dir = home.join(".agent-presets").join("biodsh");
            fs::create_dir_all(&dir).ok()?;
            fs::write(dir.join("agent.cordis.yml"), composed).ok()?;
            fs::write(dir.join("preset.yml"), "name: BioDSH 生信助手\ndescription: 面向医生与湿实验科学家的生信分析助手（BioDSH 桌面版默认）。\norder: 0\n").ok()?;
            Some(())
        })().is_some();

        let patch = home.join("cordis.patch.yml");
        let existing = fs::read_to_string(&patch).unwrap_or_default();
        let marker = |v: &str| existing.contains(&format!("# biodsh-minimal {v}"));
        if !patch.exists() || marker("v1") || marker("v2") || marker("v3") || marker("v4") || marker("v5") {
            let mut body: Vec<String> = MINIMAL_PLUGINS.iter().map(|id| format!("- id: {id}\n  disabled: true")).collect();
            let persona_yaml = PERSONA.lines().map(|l| if l.is_empty() { String::new() } else { format!("      {l}") }).collect::<Vec<_>>().join("\n");
            body.push(format!("- id: system-prompt\n  config:\n    persona: >-\n{persona_yaml}"));
            if preset_ok {
                body.push("- id: agent-presets\n  config:\n    default: biodsh".into());
            }
            // 外接 MCP 服务：每个服务一个 dsh-mcp-client 实例，模型看到的工具名是 mcp__<name>__<tool>
            for m in mcp.iter().filter(|m| m.enabled != Some(false)) {
                let name: String = m.name.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-').take(32).collect();
                if name.is_empty() { continue; }
                let mut y = format!("- id: mcp-{name}\n  name: '@deepseek-ai/dsh-mcp-client'\n  config:\n    serverName: {name}\n");
                if m.transport == "streamable-http" {
                    if m.url.trim().is_empty() { continue; }
                    y.push_str(&format!("    transport: streamable-http\n    url: {}\n", yaml_str(m.url.trim())));
                } else {
                    if m.command.trim().is_empty() { continue; }
                    y.push_str(&format!("    transport: stdio\n    command: {}\n", yaml_str(m.command.trim())));
                    if !m.args.is_empty() { y.push_str(&format!("    args: [{}]\n", m.args.iter().map(|a| yaml_str(a)).collect::<Vec<_>>().join(", "))); }
                    if !m.env.is_empty() { y.push_str("    env:\n"); for (k, v) in &m.env { y.push_str(&format!("      {k}: {}\n", yaml_str(v))); } }
                }
                y.push_str("    failOnStartupError: false\n");
                body.push(y.trim_end().to_string());
            }
            let _ = fs::write(&patch, format!("# biodsh-minimal v5 — BioDSH 精简模式 + BioDSH 人设 + MCP 接入（删除本文件并重启即可恢复 dsh 默认）\n{}\n", body.join("\n")));
        }
        let settings = home.join("settings.yaml");
        if !settings.exists() {
            let _ = fs::write(&settings, "ui-onboarding:\n  welcomeNoticeVersion: 2026-08-13.1\nlocale:\n  preference: zh\nui-theme:\n  preference: system\n");
        }
    }

    pub fn start(self: &Arc<Self>, app: &AppHandle, paths: &AppPaths, workspace: &str) -> DshStatus { self.start_with(app, paths, workspace, None, Vec::new(), &[]) }

    /// `extra_env`：额外注入给 dsh 子进程的环境变量（图像生成接口等）；`mcp`：写进 patch 的 MCP 服务。
    pub fn start_with(self: &Arc<Self>, app: &AppHandle, paths: &AppPaths, workspace: &str, offline_key: Option<String>, extra_env: Vec<(String, String)>, mcp: &[crate::settings::McpServer]) -> DshStatus {
        if self.child.lock().unwrap().is_some() { return self.status.lock().unwrap().clone(); }
        Self::ensure_home(paths, workspace, &crate::paths::resource(app, "dsh/node_modules").join("@deepseek-ai").join("dsh").join("config").join("agent-presets").join("standard"), mcp);
        crate::settings::migrate_credentials(paths);
        ensure_sitecustomize(&paths.bioenv);
        *self.status.lock().unwrap() = DshStatus { state: "starting".into(), ..Default::default() };
        self.emit(app);
        let node = node_binary(app);
        let bin = dsh_bin(app);
        if !node.exists() {
            *self.status.lock().unwrap() = DshStatus { state: "error".into(), error: Some(format!("找不到自带的 Node 运行时：{}", node.display())), ..Default::default() };
            self.push(app, paths, &format!("[error] node not found at {}", node.display()));
            return self.status.lock().unwrap().clone();
        }
        let bin_dir = venv_bin_dir(&paths.bioenv);
        let uv_dir = uv_binary(app).parent().map(Path::to_path_buf).unwrap_or_default();
        let sep = if cfg!(windows) { ";" } else { ":" };
        let node_dir = node.parent().map(Path::to_path_buf).unwrap_or_default();
        let path_env = format!("{}{sep}{}{sep}{}{sep}{}", bin_dir.display(), uv_dir.display(), node_dir.display(), std::env::var("PATH").unwrap_or_default());
        let _ = fs::create_dir_all(workspace);
        self.push(app, paths, &format!("[spawn] {} --expose-internals {} web (cwd {workspace})", node.display(), bin.display()));
        let mut cmd = Command::new(&node);
        cmd.arg("--expose-internals").arg(&bin).args(["web", "--port", "0", "--no-open"])
            .current_dir(workspace)
            .env("DSH_HOME", &paths.dsh_home)
            .env("BIODSH_HOME", &paths.root)
            .env("BIODSH_PYTHON", venv_python(&paths.bioenv))
            .env("UV_PROJECT_ENVIRONMENT", paths.bioenv.join(".venv"))
            .env("VIRTUAL_ENV", paths.bioenv.join(".venv"))
            .env("PATH", path_env)
            .env("DSH_TELEMETRY_DISABLED", "1")
            .env_remove("NODE_OPTIONS");
        if let Some(k) = offline_key { if !k.is_empty() { cmd.env("BIODSH_OFFLINE_KEY", k); } else { cmd.env("BIODSH_OFFLINE_KEY", "local"); } }
        for (k, v) in extra_env { if !v.is_empty() { cmd.env(k, v); } }
        cmd
            .stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::piped());
        #[cfg(windows)]
        { use std::os::windows::process::CommandExt; cmd.creation_flags(0x0800_0000); } // CREATE_NO_WINDOW
        let mut child = match cmd.spawn() {
            Ok(c) => c,
            Err(e) => {
                *self.status.lock().unwrap() = DshStatus { state: "error".into(), error: Some(e.to_string()), ..Default::default() };
                self.emit(app);
                return self.status.lock().unwrap().clone();
            }
        };
        let stdout = child.stdout.take();
        let stderr = child.stderr.take();
        *self.child.lock().unwrap() = Some(child);
        for stream in [stdout.map(|s| Box::new(s) as Box<dyn std::io::Read + Send>), stderr.map(|s| Box::new(s) as Box<dyn std::io::Read + Send>)].into_iter().flatten() {
            let me = Arc::clone(self);
            let app = app.clone();
            let paths = paths.clone();
            std::thread::spawn(move || {
                for line in BufReader::new(stream).lines().map_while(Result::ok) {
                    if line.trim().is_empty() { continue; }
                    if let Some(i) = line.find("http://127.0.0.1:") {
                        let url: String = line[i..].chars().take_while(|c| !c.is_whitespace()).collect();
                        let mut s = me.status.lock().unwrap();
                        if s.state == "starting" { s.state = "running".into(); s.url = Some(url); }
                    }
                    me.push(&app, &paths, &line);
                }
            });
        }
        // 监视退出
        {
            let me = Arc::clone(self);
            let app = app.clone();
            let paths = paths.clone();
            std::thread::spawn(move || loop {
                std::thread::sleep(std::time::Duration::from_millis(500));
                let mut guard = me.child.lock().unwrap();
                let Some(child) = guard.as_mut() else { break };
                match child.try_wait() {
                    Ok(Some(code)) => {
                        *guard = None;
                        drop(guard);
                        let ok = code.success();
                        { let mut s = me.status.lock().unwrap(); s.state = if ok { "stopped".into() } else { "error".into() }; if !ok { s.error = Some(format!("dsh 退出，代码 {code}")); } }
                        me.push(&app, &paths, &format!("[dsh exited with {code}]"));
                        break;
                    }
                    Ok(None) => {}
                    Err(_) => break,
                }
            });
        }
        // 最多等 60 秒拿到 URL
        for _ in 0..300 {
            std::thread::sleep(std::time::Duration::from_millis(200));
            let st = self.status.lock().unwrap().state.clone();
            if st != "starting" { break; }
        }
        if self.status.lock().unwrap().state == "starting" {
            let mut s = self.status.lock().unwrap();
            s.state = "error".into();
            s.error = Some("dsh 启动超时（60 秒内未就绪）".into());
        }
        self.emit(app);
        self.status.lock().unwrap().clone()
    }

    pub fn stop(&self, app: &AppHandle) {
        let child = self.child.lock().unwrap().take();
        if let Some(mut c) = child {
            #[cfg(windows)]
            { use std::os::windows::process::CommandExt; let _ = Command::new("taskkill").args(["/pid", &c.id().to_string(), "/T", "/F"]).creation_flags(0x0800_0000).stdout(Stdio::null()).stderr(Stdio::null()).status(); }
            let _ = c.kill();
            let _ = c.wait();
        }
        let mut s = self.status.lock().unwrap();
        s.state = "stopped".into();
        s.url = None;
        drop(s);
        self.emit(app);
    }
}

fn chrono_now() -> String {
    // 不引入 chrono：ISO 8601 近似（秒级）
    let secs = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0);
    let days = secs / 86400; let rem = secs % 86400;
    let (h, m, s) = (rem / 3600, (rem % 3600) / 60, rem % 60);
    // 民用历转换（Howard Hinnant 算法）
    let z = days as i64 + 719468; let era = z.div_euclid(146097); let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365; let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1; let mo = if mp < 10 { mp + 3 } else { mp - 9 }; let y = if mo <= 2 { y + 1 } else { y };
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{m:02}:{s:02}.000Z")
}
